# Generated by Django 5.0.14 on 2026-09-18 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='cards.vcard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vcard', 'status'], name='enquiries_e_vcard_i_f255ce_idx')],
            },
        ),
    ]
