# Generated by Django 5.0.14 on 2026-09-18 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(help_text='Chip UID reported by the NFC hardware.', max_length=64, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('material', models.CharField(choices=[('pet_plastic', 'PET Plastic'), ('wood', 'Wood'), ('metal', 'Metal')], default='pet_plastic', max_length=20)),
                ('status', models.CharField(choices=[('inventory', 'Inventory'), ('reserved', 'Reserved'), ('assigned', 'Assigned'), ('active', 'Active'), ('blocked', 'Blocked'), ('retired', 'Retired')], default='inventory', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='orders.order')),
                ('vcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='cards.vcard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='nfc_qr_nfcc_status_9cf915_idx')],
            },
        ),
    ]
