# Generated by Django 5.0.14 on 2026-09-18 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('profile_blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='profile_blocks.profilelink')),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='cards.vcard')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CardView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cards.vcard')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vcard', 'timestamp'], name='analytics_c_vcard_i_11542b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_downloads', to='cards.vcard')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vcard', 'timestamp'], name='analytics_c_vcard_i_c30ffd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyCardStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('link_clicks', models.PositiveIntegerField(default=0)),
                ('contact_downloads', models.PositiveIntegerField(default=0)),
                ('enquiries', models.PositiveIntegerField(default=0)),
                ('appointments', models.PositiveIntegerField(default=0)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='cards.vcard')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vcard', 'date'], name='analytics_d_vcard_i_f2dab2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailycardstat',
            constraint=models.UniqueConstraint(fields=('vcard', 'date'), name='unique_vcard_daily_stat'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['vcard', 'timestamp'], name='analytics_l_vcard_i_dd634e_idx'),
        ),
    ]
