# Generated by Django 5.0.14 on 2026-09-18 12:07

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='vcards/gallery/', validators=[apps.core.validators.validate_image_file])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_4feb9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vcards/products/', validators=[apps.core.validators.validate_image_file])),
                ('external_url', models.URLField(blank=True)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_a147d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('social', 'Social'), ('link', 'Link'), ('service', 'Service'), ('product', 'Product'), ('testimonial', 'Testimonial'), ('gallery', 'Gallery'), ('video', 'Video'), ('contact', 'Contact'), ('location', 'Location'), ('appointment', 'Appointment'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_f40172_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_ccea8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vcards/services/', validators=[apps.core.validators.validate_image_file])),
                ('booking_enabled', models.BooleanField(default=False)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_86e387_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_title', models.CharField(blank=True, max_length=255)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='vcards/testimonials/', validators=[apps.core.validators.validate_image_file])),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='cards.vcard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vcard', 'position'], name='profile_blo_vcard_i_5a5b82_idx')],
            },
        ),
    ]
