# Generated by Django 5.0.14 on 2026-09-18 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('welcome', 'Welcome'), ('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('new_enquiry', 'New enquiry'), ('new_appointment', 'New appointment'), ('appointment_reminder', 'Appointment reminder'), ('payment_successful', 'Payment successful'), ('payment_failed', 'Payment failed'), ('subscription_expiring', 'Subscription expiring'), ('order_received', 'Order received'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('team_invitation', 'Team invitation')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx')],
            },
        ),
    ]
